version: '2.2'

networks:
  land:

services:

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - land

  peer1.org1.land.com:
    image: hyperledger/fabric-peer:2.2
    container_name: peer1.org1.land.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=peer1.org1.land.com
      - CORE_PEER_ADDRESS=peer1.org1.land.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.land.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.land.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.land.com:9051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    volumes:
      - ../crypto-config/peerOrganizations/org1.land.com/peers/peer1.org1.land.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/org1.land.com/peers/peer1.org1.land.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/:/etc/hyperledger/channel/
    depends_on:
      - couchdb2
    ports:
      - 9051:9051
    networks:
      - land