version: "2.2"

networks:
  land:

services:

  ca-org1:
    image: hyperledger/fabric-ca:1.4.8
    container_name: ca.org1.land.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.land.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.land.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org1.land.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/org1.land.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-config/peerOrganizations/org1.land.com/tlsca:/etc/hyperledger/fabric-ca-server-tls
    hostname: ca.org1.land.com
    networks:
      - land

  ca-org2:
    image: hyperledger/fabric-ca:1.4.8
    container_name: ca.org2.land.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.land.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.land.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org2.land.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/org2.land.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-config/peerOrganizations/org2.land.com/tlsca:/etc/hyperledger/fabric-ca-server-tls
    hostname: ca.org2.land.com
    networks:
      - land

  orderer.land.com:
    image: hyperledger/fabric-orderer:2.2
    container_name: orderer.land.com
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - land
    volumes:
      - ../channel/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../crypto-config/ordererOrganizations/land.com/orderers/orderer.land.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/land.com/orderers/orderer.land.com/tls:/var/hyperledger/orderer/tls

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - land

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - land

  peer0.org1.land.com:
    container_name: peer0.org1.land.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=peer0.org1.land.com
      - CORE_PEER_ADDRESS=peer0.org1.land.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.land.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.land.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.land.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
      - 9443:9443
    volumes:
      - ../crypto-config/peerOrganizations/org1.land.com/peers/peer0.org1.land.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/org1.land.com/peers/peer0.org1.land.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/:/etc/hyperledger/channel/
    networks:
      - land

  peer0.org2.land.com:
    container_name: peer0.org2.land.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ID=peer0.org2.land.com
      - CORE_PEER_ADDRESS=peer0.org2.land.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.land.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.land.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.land.com:8051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    ports:
      - 8051:8051
      - 9444:9444
    volumes:
      - ../crypto-config/peerOrganizations/org2.land.com/peers/peer0.org2.land.com/msp:/etc/hyperledger/crypto/peer/msp
      - ../crypto-config/peerOrganizations/org2.land.com/peers/peer0.org2.land.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./channel/:/etc/hyperledger/channel/
    networks:
      - land

  # prometheus: 
  #   container_name: prometheus
  #   image: prom/prometheus 
  #   ports:
  #     - 9090:9090
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml       
  #   volumes: 
  #       - ./prometheus.yml:/etc/prometheus/prometheus.yml 
  #   networks: 
  #       - land
  #   depends_on:
  #      - orderer.land.com
  #      - peer0.org1.land.com
  #      - peer0.org2.land.com  

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - land
  #   depends_on:
  #     - prometheus         