global: 
  scrape_interval: 15s 
  evaluation_interval: 15s 
scrape_configs: 
- job_name: 'prometheus' 
  scrape_interval: 10s 
  static_configs: 
  - targets: ['localhost:9090'] 
- job_name: 'hyperledger_metrics' 
  scrape_interval: 10s 
  static_configs: 
  - targets: ['orderer.land.com:8443','peer0.org1.land.com:9443','peer0.org2.land.com:9444']